# Generated by Django 4.2.11 on 2026-05-07 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('aadhaar_number', models.CharField(max_length=12)),
                ('pan_number', models.CharField(max_length=10)),
                ('employment_type', models.CharField(choices=[('Student', 'Student'), ('Salaried', 'Salaried'), ('Self-Employed', 'Self-Employed'), ('Business', 'Business'), ('Government Employee', 'Government Employee')], max_length=30)),
                ('loan_type', models.CharField(choices=[('Education Loan', 'Education Loan'), ('Personal Loan', 'Personal Loan'), ('Home Loan', 'Home Loan'), ('Vehicle Loan', 'Vehicle Loan'), ('Business Loan', 'Business Loan')], max_length=30)),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tenure_months', models.PositiveIntegerField(choices=[(6, '6 Months'), (12, '1 Year'), (24, '2 Years'), (60, '5 Years')])),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=80)),
                ('pincode', models.CharField(max_length=10)),
                ('purpose', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
